name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.ECR_REGISTRY }}/${{ secrets.IMAGE_NAME }}:$GITHUB_SHA .
        docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.IMAGE_NAME }}:$GITHUB_SHA 

    # - name: Push Docker image to ECR
    #   run: |
    #     docker push $ECR_REGISTRY/$IMAGE_NAME:$GITHUB_SHA
    #     docker push $ECR_REGISTRY/$IMAGE_NAME:latest

    - name: Configure kubectl
      uses: azure/k8s-set-context@v1
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}

    - name: Deploy to EKS
      run: kubectl apply -f deployment.yaml


























# name: Deploy to ECR and EKS

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Login to AWS ECR
#         uses: aws-actions/amazon-ecr-login@v1

#       - name: Build Docker image and push to ECR
#         run: |
#           docker build -t ${{ secrets.ECR_REGISTRY }}/${{ secrets.IMAGE_NAME }}:$GITHUB_SHA .
#           docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.IMAGE_NAME }}:$GITHUB_SHA

#       - name: Configure AWS credentials for EKS
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: ap-south-1

#       - name: Deploy frontend to EKS 
#         run: |
#           kubectl apply -f deployment.yaml
          
