name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: docker build -t frontend-app .

      - name: Tag Docker image
        run: docker tag frontend-app:latest 767398004402.dkr.ecr.ap-south-1.amazonaws.com/frontend-app:latest

      - name: Push Docker image to Amazon ECR
        run: docker push 767398004402.dkr.ecr.ap-south-1.amazonaws.com/frontend-app:latest
        
        #delpoy

      - name: Update Kubernetes deployment
        run: |
          aws eks --region ap-south-1 update-kubeconfig --name my-cluster
          kubectl apply -f deployment.yaml



# # name: Deploy Frontend App

# # on:
# #   push:
# #     branches:
# #       - main

# # jobs:
# #   deploy:
# #     runs-on: ubuntu-latest

# #     steps:
# #       - name: Checkout Repository
# #         uses: actions/checkout@v2

# #       - name: Login to AWS ECR
# #         run: echo "${{ secrets.AWS_ACCESS_KEY_ID }}" | docker login --username AWS --password-stdin 767398004402.dkr.ecr.ap-south-1.amazonaws.com

# #       - name: Build Docker Image
# #         run: |
# #           docker build -t frontend-app .
# #           docker tag frontend-app:latest 767398004402.dkr.ecr.ap-south-1.amazonaws.com/frontend-app:latest

# #       - name: Push Docker Image to ECR
# #         run: docker push 767398004402.dkr.ecr.ap-south-1.amazonaws.com/frontend-app:latest

# #       - name: Update kube config
# #         run: aws eks --region ap-south-1 update-kubeconfig --name my-cluster
# #         #deploy

# #       - name: Deploy to EKS
# #         run: kubectl apply -f deployment.yaml


# name: Deploy Frontend App

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Login to AWS ECR
#         run: echo "${{ secrets.AWS_ACCESS_KEY_ID }}" | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

#       - name: Build Docker Image
#         run: |
#           docker build -t frontend-app .
#           docker tag frontend-app:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/frontend-app:latest

#       - name: Push Docker Image to ECR
#         run: docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/frontend-app:latest

#       - name: Update kube config
#         run: aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }}

#       - name: Deploy to EKS
#         run: kubectl apply -f deployment.yaml

