name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker image
      run: |
        docker build -t $ECR_REGISTRY/$IMAGE_NAME:$GITHUB_SHA .
        docker tag $ECR_REGISTRY/$IMAGE_NAME:$GITHUB_SHA $ECR_REGISTRY/$IMAGE_NAME:latest

    - name: Push Docker image to ECR
      run: |
        docker push $ECR_REGISTRY/$IMAGE_NAME:$GITHUB_SHA
        docker push $ECR_REGISTRY/$IMAGE_NAME:latest

    - name: Configure kubectl
      uses: azure/k8s-set-context@v1
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}

    - name: Deploy to EKS
      run: kubectl apply -f deployment.yaml
