name: Deploy to ECR and EKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry: ${{ secrets.ECR_REGISTRY }}
          region: ap-south-1

      - name: Build Docker image and push to ECR
        run: |
          docker build -t ${{ secrets.ECR_REGISTRY }}/${{ secrets.IMAGE_NAME }}:$GITHUB_SHA .
          docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.IMAGE_NAME }}:$GITHUB_SHA

      - name: Configure kubectl
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}

      - name: Deploy frontend to EKS
        run: |
          kubectl apply -f deployment.yaml

