name: Deploy Frontend App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to AWS ECR
        run: echo "${{ secrets.AWS_ACCESS_KEY_ID }}" | docker login --username AWS --password-stdin 767398004402.dkr.ecr.ap-south-1.amazonaws.com/flask_app_ecr_eks

      - name: Update kube config
        run: aws eks update-kubeconfig --region ap-south-1 --name my-cluster

      - name: Build Docker Image
        run: |
          docker build -t frontend-app .
          docker tag frontend-app:latest 767398004402.dkr.ecr.ap-south-1.amazonaws.com/flask_app_ecr_eks:latest

      - name: Push Docker Image to ECR
        run: docker push 767398004402.dkr.ecr.ap-south-1.amazonaws.com/flask_app_ecr_eks:latest
      #deploy
      - name: Deploy to EKS
        run: kubectl apply -f deployment.yaml
